"use client";

import { useEditor, EditorContent, type Content } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Link from "@tiptap/extension-link";
import TaskList from "@tiptap/extension-task-list";
import TaskItem from "@tiptap/extension-task-item";
import Placeholder from "@tiptap/extension-placeholder";
import Underline from "@tiptap/extension-underline";
import Image from "@tiptap/extension-image";
import Gapcursor from "@tiptap/extension-gapcursor";
import { Extension } from "@tiptap/core";
import { Plugin, PluginKey } from "@tiptap/pm/state";
import { common, createLowlight } from "lowlight";
import { createMermaidCodeBlock } from "./MermaidCodeBlock";
import { useEffect, useState, useCallback, useRef } from "react";
import {
  PenLine,
  Code,
  BookOpen,
  FileText,
  ListCollapse,
  ClipboardList,
  Image as ImageIcon,
} from "lucide-react";
import { WikiLink } from "./WikiLinkExtension";
import { WikiLinkSuggestion } from "./WikiLinkSuggestion";
import { SlashCommandMenu } from "./SlashCommandMenu";
import { BubbleToolbar } from "./BubbleToolbar";
import { Callout } from "./CalloutExtension";
import { Button } from "@/components/ui/button";
import { AiResultDialog } from "@/components/ai/AiResultDialog";
import { noteAssist } from "@/lib/api/ai";
import { useAiChat, type PageAiAction } from "@/lib/ai-chat-context";

const lowlight = createLowlight(common);

const NOTE_AI_ACTIONS = [
  { label: "Continue Writing", action: "continue", icon: PenLine },
  { label: "Generate Example", action: "generate_example", icon: Code },
  { label: "Explain", action: "explain", icon: BookOpen },
  { label: "Add Details", action: "add_details", icon: FileText },
  { label: "Summarize", action: "summarize", icon: ListCollapse },
  { label: "Generate Quiz", action: "generate_quiz", icon: ClipboardList },
];

/**
 * Custom extension to ensure there's always an empty paragraph at the end of the document.
 */
const TrailingNode = Extension.create({
  name: "trailingNode",
  addProseMirrorPlugins() {
    const plugin = new Plugin({
      key: new PluginKey("trailingNode"),
      appendTransaction: (transactions, oldState, newState) => {
        const { doc, tr } = newState;
        const lastNode = doc.lastChild;
        if (lastNode && lastNode.type.name !== "paragraph") {
          const type = newState.schema.nodes.paragraph;
          return tr.insert(doc.content.size, type.create());
        }
        return null;
      },
    });
    return [plugin];
  },
});

interface TipTapEditorProps {
  content: string | null;
  onUpdate: (json: string, text: string) => void;
  editable?: boolean;
  onNavigateToNote?: (noteId: string) => void;
}

export function TipTapEditor({
  content,
  onUpdate,
  editable = true,
  onNavigateToNote,
}: TipTapEditorProps) {
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResultOpen, setAiResultOpen] = useState(false);
  const [aiResultContent, setAiResultContent] = useState("");
  const [aiResultTitle, setAiResultTitle] = useState("");
  const { setPageActions, clearPageActions } = useAiChat();
  const editorRef = useRef<ReturnType<typeof useEditor>>(null) as React.MutableRefObject<ReturnType<typeof useEditor>>;

  const handleAiAction = useCallback(
    async (action: string, textAboveCursor: string, fullNoteText: string) => {
      const actionLabels: Record<string, string> = {
        continue: "Continue Writing",
        generate_example: "Generate Example",
        generate_diagram: "Generate Diagram",
        explain: "Explain",
        add_details: "Add Details",
        summarize: "Summarize",
        generate_quiz: "Generate Quiz",
      };

      setAiLoading(true);
      setAiResultTitle(`AI ${actionLabels[action] || action}`);
      setAiResultContent("");
      setAiResultOpen(true);

      try {
        // Truncate text to avoid huge payloads that crash the API
        const truncatedAbove = textAboveCursor.slice(-3000);
        const truncatedFull = fullNoteText.slice(-5000);
        
        const result = await noteAssist(action, truncatedAbove, truncatedFull);
        setAiResultContent(result.content || "No content generated by AI.");
      } catch (error: any) {
        console.error("AI Action Error:", error);
        const msg = error.response?.data?.message || error.message || "Unknown error";
        setAiResultContent(`Failed to process text: ${msg}. Please check your AI settings.`);
      } finally {
        setAiLoading(false);
      }
    },
    []
  );

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        heading: { levels: [1, 2, 3] },
        codeBlock: false, // Replaced by CodeBlockLowlight
      }),
      Gapcursor,
      TrailingNode,
      Image.configure({
        HTMLAttributes: {
          class: "rounded-lg border border-border shadow-sm max-w-full h-auto my-4",
        },
      }),
      createMermaidCodeBlock(lowlight),
      Link.configure({
        openOnClick: false,
        HTMLAttributes: { class: "text-primary underline cursor-pointer" },
      }),
      TaskList,
      TaskItem.configure({ nested: true }),
      Placeholder.configure({
        placeholder: "Type '/' for commands, '[[' to link notes",
      }),
      Underline,
      Callout,
      WikiLink.configure({
        onNavigate: onNavigateToNote,
      }),
    ],
    content: content ? tryParseJson(content) : "",
    editable,
    editorProps: {
      attributes: {
        class:
          "tiptap prose max-w-none focus:outline-none min-h-[400px] px-6 py-4",
      },
    },
    onUpdate: ({ editor }) => {
      const json = JSON.stringify(editor.getJSON());
      const text = editor.getText();
      onUpdate(json, text);
    },
  });

  // Keep editorRef in sync
  editorRef.current = editor;

  // Register page-specific AI actions with the global button
  useEffect(() => {
    if (!editable) return;

    const actions: PageAiAction[] = NOTE_AI_ACTIONS.map((item) => ({
      label: item.label,
      action: item.action,
      icon: item.icon,
      onAction: () => {
        const ed = editorRef.current;
        if (!ed) return;
        const { from } = ed.state.selection;
        const textAboveCursor = ed.state.doc.textBetween(0, from, "\n");
        const fullNoteText = ed.getText();
        handleAiAction(item.action, textAboveCursor, fullNoteText);
      },
    }));

    setPageActions(actions);
    return () => clearPageActions();
  }, [editable, setPageActions, clearPageActions, handleAiAction]);

  useEffect(() => {
    if (!editor) return;
    if (content) {
      const parsed = tryParseJson(content);
      const currentJson = JSON.stringify(editor.getJSON());
      const newJson = typeof parsed === "string" ? parsed : JSON.stringify(parsed);
      if (currentJson !== newJson) {
        editor.commands.setContent(parsed);
      }
    } else {
      editor.commands.clearContent();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [content, editor]);

  if (!editor) return null;

  function handleInsertAtCursor() {
    if (!editor) return;
    const { from } = editor.state.selection;
    // Convert markdown to HTML so TipTap parses it into proper nodes (code blocks, etc.)
    const htmlContent = markdownFencesToHtml(aiResultContent);
    editor.chain().focus().insertContentAt(from, htmlContent).run();
    setAiResultOpen(false);
  }

  function handleInsertAtEnd() {
    if (!editor) return;
    const endPos = editor.state.doc.content.size;
    // Convert markdown to HTML so TipTap parses it into proper nodes
    const htmlContent = markdownFencesToHtml(aiResultContent);
    editor.chain().focus().insertContentAt(endPos, "\n\n" + htmlContent).run();
    setAiResultOpen(false);
  }

  return (
    <div className="bg-background relative">
      <div className="relative">
        <EditorContent editor={editor} />
        <BubbleToolbar editor={editor} />
        <WikiLinkSuggestion editor={editor} />
        <SlashCommandMenu editor={editor} onAiAction={handleAiAction} />
        <div className="absolute top-2 right-2 flex gap-2 z-10">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              const input = document.createElement("input");
              input.type = "file";
              input.accept = "image/*";
              input.onchange = async () => {
                if (input.files?.length) {
                  const file = input.files[0];
                  const formData = new FormData();
                  formData.append("file", file);
                  try {
                    const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL || (typeof window !== 'undefined' ? `${window.location.protocol}//${window.location.hostname}:8080` : 'http://localhost:8080');
                    const response = await fetch(`${apiBaseUrl}/api/upload`, {
                      method: "POST",
                      body: formData,
                      headers: {
                        "Authorization": `Bearer ${localStorage.getItem("token")}`
                      }
                    });
                    const data = await response.json();
                    if (data.url) {
                      const url = apiBaseUrl + data.url;
                      editor.chain().focus().setImage({ src: url }).run();
                    }
                  } catch (error) {
                    console.error("Image upload failed", error);
                  }
                }
              };
              input.click();
            }}
            className="h-8 w-8 p-0"
            title="Attach Image"
          >
            <ImageIcon className="h-4 w-4" />
          </Button>
        </div>
      </div>

      <AiResultDialog
        open={aiResultOpen}
        onOpenChange={setAiResultOpen}
        title={aiResultTitle}
        content={aiResultContent}
        isLoading={aiLoading}
        actions={[
          { label: "Insert at Cursor", onClick: handleInsertAtCursor },
          { label: "Insert at End", onClick: handleInsertAtEnd, variant: "outline" },
        ]}
      />
    </div>
  );
}

/**
 * Expand a one-liner mermaid string into proper multi-line syntax.
 * Handles: semicolons as line separators, style/classDef/linkStyle directives,
 * and graph type declarations that need their own line.
 */
function expandMermaidOneLiner(code: string): string {
  let result = code;
  // Expand semicolons to newlines
  if (!result.includes("\n") && result.includes(";")) {
    result = result.replace(/;\s*/g, "\n");
  }
  // Ensure graph/flowchart declaration is on its own line
  result = result.replace(/^((?:graph|flowchart)\s+(?:TD|TB|BT|RL|LR))\s+/, "$1\n");
  // Put style / classDef / linkStyle / class directives on their own lines
  result = result.replace(/\s+(style\s)/g, "\n$1");
  result = result.replace(/\s+(classDef\s)/g, "\n$1");
  result = result.replace(/\s+(linkStyle\s)/g, "\n$1");
  result = result.replace(/\s+(class\s)/g, "\n$1");
  return result.trim();
}

/**
 * Convert markdown code fences (```lang ... ```) into HTML <pre><code> blocks
 * so TipTap creates proper codeBlock nodes instead of plain-text paragraphs.
 */
function markdownFencesToHtml(text: string): string {
  const parts: string[] = [];
  let lastIdx = 0;
  const fenceRe = /```(\w*)\s*([\s\S]*?)```/g;
  let match;
  while ((match = fenceRe.exec(text)) !== null) {
    const before = text.slice(lastIdx, match.index).trim();
    if (before) {
      parts.push(
        before
          .split(/\n/)
          .map((line) => `<p>${line}</p>`)
          .join("")
      );
    }
    const lang = match[1] || "";
    let code = match[2].trim();
    if (lang === "mermaid") {
      code = expandMermaidOneLiner(code);
    }
    const escaped = code
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    parts.push(
      `<pre><code class="language-${lang}">${escaped}</code></pre>`
    );
    lastIdx = match.index + match[0].length;
  }
  const remaining = text.slice(lastIdx).trim();
  if (remaining) {
    parts.push(
      remaining
        .split(/\n/)
        .map((line) => `<p>${line}</p>`)
        .join("")
    );
  }
  return parts.join("");
}

/**
 * Walk TipTap JSON and convert paragraph nodes containing markdown code fences
 * into proper codeBlock nodes.
 */
function transformJsonContent(doc: Record<string, unknown>): Record<string, unknown> {
  if (!doc || typeof doc !== "object" || !Array.isArray((doc as { content?: unknown[] }).content)) return doc;
  const content = (doc as { content: Array<Record<string, unknown>> }).content;
  const newContent: Record<string, unknown>[] = [];

  for (const node of content) {
    if (node.type === "paragraph" && Array.isArray(node.content)) {
      // Extract full text of the paragraph
      const text = (node.content as Array<{ text?: string }>)
        .map((c) => c.text || "")
        .join("");
      if (text.includes("```")) {
        const fenceRe = /```(\w*)\s*([\s\S]*?)```/g;
        let match;
        let lastIdx = 0;
        while ((match = fenceRe.exec(text)) !== null) {
          const before = text.slice(lastIdx, match.index).trim();
          if (before) {
            newContent.push({
              type: "paragraph",
              content: [{ type: "text", text: before }],
            });
          }
          const lang = match[1] || "";
          let code = match[2].trim();
          if (lang === "mermaid") {
            code = expandMermaidOneLiner(code);
          }
          newContent.push({
            type: "codeBlock",
            attrs: { language: lang },
            content: [{ type: "text", text: code }],
          });
          lastIdx = match.index + match[0].length;
        }
        const remaining = text.slice(lastIdx).trim();
        if (remaining) {
          newContent.push({
            type: "paragraph",
            content: [{ type: "text", text: remaining }],
          });
        }
        continue;
      }
    }
    newContent.push(node);
  }

  return { ...doc, content: newContent };
}

function tryParseJson(content: string): Content {
  try {
    const parsed = JSON.parse(content);
    // Transform JSON content to fix embedded code fences in paragraphs
    return transformJsonContent(parsed) as Content;
  } catch {
    // Not JSON — treat as markdown/plain text
    if (content.includes("```")) {
      return markdownFencesToHtml(content);
    }
    return content;
  }
}
