/**
 * Shared utility for sanitizing Mermaid.js chart code.
 * Fixes common syntax errors generated by LLMs.
 */

const CLOSE_BRACKET: Record<string, string> = { "[": "]", "(": ")", "{": "}" };
const SPECIAL_CHARS = /[()[\]{}<>&#;]/;

/**
 * Sanitize Mermaid chart text to fix common AI-generated syntax issues.
 * - Expands one-liners with semicolons.
 * - Ensures graph/flowchart declarations are on their own lines.
 * - Quotes labels containing special characters.
 * - Handles bracket-depth matching for nested parentheses.
 */
export function sanitizeMermaid(code: string): string {
  if (!code) return "";

  let result = code;

  // 1. Basic preprocessing: Expand semicolons to newlines if it's a one-liner
  if (!result.includes("\n") && result.includes(";")) {
    result = result.replace(/;\s*/g, "\n");
  }

  // 2. Ensure graph type declaration is on its own line (LLMs often put content right after TD/LR)
  result = result.replace(/^((?:graph|flowchart)\s+(?:TD|TB|BT|RL|LR))\s+/, "$1\n");

  // 3. Line-by-line advanced sanitization
  return result
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();
      
      // Skip directive / style / empty lines
      if (
        !trimmed ||
        trimmed.startsWith("%%") ||
        trimmed.startsWith("graph ") ||
        trimmed.startsWith("flowchart ") ||
        trimmed.startsWith("classDef ") ||
        trimmed.startsWith("style ") ||
        trimmed.startsWith("linkStyle ")
      ) {
        // Remove trailing semicolons on style lines
        return line.replace(/;\s*$/, "");
      }

      // Remove trailing semicolons from standard lines
      let l = line.replace(/;\s*$/, "");

      // Walk through the line and quote labels that contain special chars
      let finalLine = "";
      let i = 0;
      while (i < l.length) {
        const ch = l[i];
        
        // Detect node label start: a word char immediately before [ ( or {
        // e.g. A[Label]
        if ((ch === "[" || ch === "(" || ch === "{") && i > 0 && /\w/.test(l[i - 1])) {
          const open = ch;
          const close = CLOSE_BRACKET[open];
          
          // Find matching close bracket with depth tracking
          let depth = 1;
          let j = i + 1;
          while (j < l.length && depth > 0) {
            if (l[j] === open) depth++;
            else if (l[j] === close) depth--;
            j++;
          }
          
          const content = l.slice(i + 1, j - 1);
          
          // Already quoted — keep as is
          if (content.startsWith('"') && content.endsWith('"')) {
            finalLine += open + content + close;
          } 
          // Contains special chars — wrap in quotes
          else if (SPECIAL_CHARS.test(content)) {
            finalLine += open + '"' + content.replace(/"/g, "'") + '"' + close;
          } 
          else {
            finalLine += open + content + close;
          }
          i = j;
        } else {
          finalLine += ch;
          i++;
        }
      }
      return finalLine;
    })
    .join("\n");
}
